### ISSUE TITLE
fail

### ISSUE THREAD

**Issue by jorgenskogmo** [hobbyquaker/node-movehub#1]
Hm, this looks amazing - doesnt seem to work here though...

yarn install
node test.js
> ble-ready true

and then nothing happens. (yes, I clicked the connect btn on the boost)

node: v8.9.4
macos: 10.13

(Same happens with Wedo2, so it could be sth on my side...)

Thanks in advance!

**Comment by hobbyquaker** [comment]
Sry for the long delay. Only thing I can think of is that your Move Hub has another Service UUID than that I hardcoded in https://github.com/hobbyquaker/node-movehub/blob/master/movehub.js#L30
